### ISSUE TITLE
Is it possible to pass the event?

### ISSUE THREAD

**Issue by seriouz** [sven5/Blazor#1]
Is it possible to pass the event to the c# side and call a preventDefault() on it from c#?

**Comment by sven5** [comment]
Currently I didn't find any way to do this. The interaction in Blazor between JS events and C# will change in the future, the API currently is not complete. In the future they will extend the Blazor API to be able to call preventDefault() from C# - please see [here.](https://github.com/aspnet/Blazor/issues/1073)
