### ISSUE TITLE
Package Microsoft.AspNetCore.Blazor.Cli 0.8.0-preview-19104-04 is not compatible with netcoreapp2.2 

### ISSUE THREAD

**Issue by sybaris** [sven5/Blazor#3]
Hi,

Trying to build your project, I have the following error :
"Error	NU1202	Package Microsoft.AspNetCore.Blazor.Cli 0.8.0-preview-19104-04 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.AspNetCore.Blazor.Cli 0.8.0-preview-19104-04 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)	BlazorDemo.App	D:\Temp\Blazor-master\HelloWorldDragDrop\BlazorDemo.App\BlazorDemo.App.csproj"

Any help would be appreciated...

Note that the link "https://blazordemo.azurewebsites.net/" is down...

Thanks for advance.
Sybaris

**Comment by sven5** [comment]
Hi @sybaris 
Yes you're right. Please apologize I didn't update the project to new Blazor and .NET Core environments. This was only a test/demo project with Blazor v0.5

**Comment by sybaris** [comment]
Hi,
It doesn't matter.
I found another example/tuto here : https://chrissainty.com/investigating-drag-and-drop-with-blazor/ and here : https://github.com/chrissainty/SimpleDragAndDropWithBlazor
Regards
Sybaris
